config/routes.rb
Rails.application.routes.draw do
  root 'weather#index'
  get '/search', to: 'weather#search'
  post '/search', to: 'weather#search'
  get '/history', to: 'weather#history'
  delete '/history/:id', to: 'weather#destroy', as: :delete_weather_data
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/weather_data.rb
class WeatherData < ApplicationRecord
  validates :city, presence: true, uniqueness: true
  validates :temperature, presence: true

  def self.create_from_weather_data(city, temperature, description)
    weather_data = find_or_initialize_by(city: city)
    weather_data.update(temperature: temperature, description: description, query_time: Time.current)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  require 'httparty'

  def index
  end

  def search
    city = params[:city]
    response = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?q=#{city}&appid=8b7a53c5908ca1fd6e95d5c642220cbb")
    weather_data = JSON.parse(response.body) if response.ok?
    weather_data['main']['temp'] = convert_to_celsius(weather_data['main']['temp']) if weather_data

    @weather_data = weather_data

    if weather_data
      WeatherData.create_from_weather_data(city, weather_data['main']['temp'], weather_data['weather'][0]['description'])
    end

    respond_to do |format|
      format.html { render partial: 'weather_result', locals: { weather_data: @weather_data } }
    end
  end

  def history
    @weather_data_history = WeatherData.order(created_at: :desc)
  end

  def destroy
    weather_data = WeatherData.find(params[:id])
    weather_data.destroy
    redirect_to history_path, notice: 'Weather data deleted successfully.'
  end

  private

  def convert_to_celsius(temp_kelvin)
    (temp_kelvin.to_f - 273.15).round(2)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/_weather_result.html.erb
<div class="card text-center">
  <% if weather_data %>
    <div class="card-body">
      <h1 class="card-title">Clima en <%= weather_data['name'] %></h1>
      <p class="card-text">Temperatura: <%= weather_data['main']['temp'] %> °C</p>
      <p class="card-text">Descripción del clima: <%= weather_data['weather'][0]['description'] %></p>
    </div>
  <% else %>
    <div class="card-body">
      <p class="card-text">No se encontraron datos para esa ciudad.</p>
    </div>
  <% end %>
</div>

app/views/weather/history.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Historial del Clima</title>
</head>
<body>
<div class="container mt-5">
  <h1 class="text-center mb-4">Historial del Clima</h1>
  <% if @weather_data_history.any? %>
    <ul class="list-group">
      <% @weather_data_history.each do |weather_data| %>
        <li class="list-group-item d-flex justify-content-center align-items-center flex-column">
          <p class="mb-0">Ciudad: <%= weather_data.city %></p>
            <p class="mb-0">Temperatura: <%= weather_data.temperature %> °C</p>
            <p class="mb-0">Descripción del clima: <%= weather_data.description %></p>
            <p class="mb-0">Hora de consulta: <%= weather_data.created_at %></p>
            <%= button_to 'Eliminar', delete_weather_data_path(weather_data), method: :delete, data: { confirm: 'Are you sure you want to delete this weather data?' }, class: 'btn btn-danger mt-2' %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center">No hay datos disponibles en el historial del clima.</p>
  <% end %>
  <%= link_to 'Regresar', root_path, class: 'btn btn-primary mt-3' %>
  </div>
</body>
</html>

app/views/weather/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather App</title>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css', media: 'all', 'data-turbo-track': 'reload' %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <div class="container mt-5">
    <%= form_tag('/search', method: :post, id: 'weather-form', class: 'mb-3') do %>
      <div class="d-flex justify-content-center align-items-center">
        <label for="city" class="me-2">Ciudad:</label>
        <%= text_field_tag :city, '', id: 'city', class: 'form-control me-2' %>
        <%= submit_tag "Buscar", id: 'search-button', disabled: false, class: 'btn btn-primary' %>
      </div>
    <% end %>

    <div id="weather-results" class="d-flex justify-content-center">
      <%= render partial: 'weather_result', locals: { weather_data: @weather_data } %>
    </div>

    <%= link_to 'Historial', history_path, class: 'btn btn-secondary mt-3' %>
  </div>

  <script>
    const weatherForm = document.getElementById("weather-form");
    const weatherResults = document.getElementById("weather-results");

    weatherForm.addEventListener("submit", function(event) {
      event.preventDefault();
      const city = document.getElementById("city").value;

      fetch(`/search?city=${city}`, { headers: { "Turbo-Frame": "weather-results" } })
        .then(response => response.text())
        .then(data => weatherResults.innerHTML = data);
    });
  </script>
</body>
</html>

app/views/weather/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather App</title>
  </head>
  <body>
    <%= form_tag('/search', method: :post) do%>
      <label for="city">City:</label>
      <%= text_field_tag :city, '', id: 'city' %>
      <%= submit_tag "Search" %>
    <% end %>

  </body>
</html>